# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventorySystem.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15inventorySystem.proto\x12\x17service.inventorySystem\"{\n\x04\x42ook\x12\x0c\n\x04isbn\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12-\n\x05genre\x18\x04 \x01(\x0e\x32\x1e.service.inventorySystem.Genre\x12\x17\n\x0fpublishing_year\x18\x05 \x01(\x05\"\x8d\x01\n\x0finventorySystem\x12\x0c\n\x04isbn\x18\x01 \x01(\t\x12-\n\x04\x62ook\x18\x02 \x01(\x0b\x32\x1d.service.inventorySystem.BookH\x00\x12/\n\x06status\x18\x03 \x01(\x0e\x32\x1f.service.inventorySystem.StatusB\x0c\n\nbook_oneOf\"\x1b\n\x08response\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x14\n\x04isbn\x12\x0c\n\x04isbn\x18\x01 \x01(\t*0\n\x06Status\x12\x10\n\x0cSTATUS_TAKEN\x10\x00\x12\x14\n\x10STATUS_AVAILABLE\x10\x01*Y\n\x05Genre\x12\x11\n\rGENRE_MYSTERY\x10\x00\x12\x11\n\rGENRE_FICTION\x10\x01\x12\x13\n\x0fGENRE_BIOGRAPHY\x10\x02\x12\x15\n\x11GENRE_NON_FICTION\x10\x03\x32\xa4\x01\n\tInventory\x12N\n\ncreateBook\x12\x1d.service.inventorySystem.Book\x1a!.service.inventorySystem.response\x12G\n\x07getBook\x12\x1d.service.inventorySystem.isbn\x1a\x1d.service.inventorySystem.Bookb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventorySystem_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STATUS._serialized_start=370
  _STATUS._serialized_end=418
  _GENRE._serialized_start=420
  _GENRE._serialized_end=509
  _BOOK._serialized_start=50
  _BOOK._serialized_end=173
  _INVENTORYSYSTEM._serialized_start=176
  _INVENTORYSYSTEM._serialized_end=317
  _RESPONSE._serialized_start=319
  _RESPONSE._serialized_end=346
  _ISBN._serialized_start=348
  _ISBN._serialized_end=368
  _INVENTORY._serialized_start=512
  _INVENTORY._serialized_end=676
# @@protoc_insertion_point(module_scope)
